version: 1.0.{build}
image: Visual Studio 2022
branches:
  only:
    - main
environment:
  deploy_username:
    secure: ZumRpgIeGcRgW3H7yXK0bQ==
  deploy_password:
    secure: SFAvHfsz398LTl83QbS5gw==
  deploy_server:
    secure: UHp6oceWoeJTc5juzkMgEsCJR5MBzNv7nhBqXvqpIUo4hUMGidMiQCxvL350tg3XwANaIFb7JYsdXkgZIlAhZ77Co3LYvdNgbY7QarYjgpXqIfcQuHMYGo7EZJf7Q2KGdnZKJjkKwFABi4jq99yVPg==
  deploy_website:
    secure: u6Ynhp0KK4/aOql8Nl3qyQiPOLaGA4ZEz3Gj+AKai/3iemBhZVdaZwmbnvJePiPM
  db_server:
    secure: GENtSiIHJlcMVdOs9CjeQw==
  db_name:
    secure: WrPAgPpTyM3R6EL58lnCDg==
  db_username:
    secure: WrPAgPpTyM3R6EL58lnCDg==
  db_password:
    secure: SFAvHfsz398LTl83QbS5gw==
install:
  - ps: >-
      $file = "./Api/appsettings.Production.json";
      (Get-Content $file).Replace("{db_server}", $env:db_server).Replace("{db_name}", $env:db_name).Replace("{db_username}", $env:db_username).Replace("{db_password}", $env:db_password) | Set-Content $file
build_script:
  - cmd: dotnet publish --framework net8.0 /p:EnvironmentName=Production --self-contained true -r win-x64 Api --output %appveyor_build_folder%\dist
test_script:
  # Ejecuta tests  
  - dotnet test --configuration Release --runtime win-x64
  - cd ..
before_deploy:
  # Aplica migraciones pendientes
  - dotnet tool install dotnet-ef --global --version 8.0.0
  - ps: $DefaultConnectionString = (Get-Content appsettings.Production.json | ConvertFrom-Json).ConnectionStrings.Default
  - ps: dotnet ef database update --connection $DefaultConnectionString
artifacts:
  - path: dist
deploy:
  - provider: WebDeploy
    remove_files: true
    skip_dirs: \\App_Data;\\logs;\\aspnet_client;
    server: $(deploy_server)
    website: $(deploy_website)
    username: $(deploy_username)
    password: $(deploy_password)
    ntlm: false
